// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Autogenerated code", Scope = "namespaceanddescendants", Target = "RepoCat.Portal.Data.Migrations")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:RepoCat.Portal.Areas.Catalog.Models.ProjectInfoViewModel.ProjectUri")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:RepoCat.Portal.Areas.Catalog.Models.ComponentManifestViewModel.DocumentationUri")]
