// -----------------------------------------------------------------------
//  <copyright file="GlobalSuppressions.cs" company="bartosz.jarmuz@gmail.com">
//   Copyright (c) Bartosz Jarmuż. All rights reserved.
//  </copyright>
// -----------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Autogenerated code", Scope = "namespaceanddescendants", Target = "RepoCat.Portal.Data.Migrations")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:RepoCat.Portal.Areas.Catalog.Models.ProjectInfoViewModel.ProjectUri")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:RepoCat.Portal.Areas.Catalog.Models.ComponentManifestViewModel.DocumentationUri")]
